name: Setup Python + uv
description: Install Python and dependencies using uv
inputs:
  python-version:
    required: true
    description: Python version
  dependency-groups:
    required: false
    description: Dependency groups to install defined in pyproject.toml
    default: ""

runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      shell: bash
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install dependencies
      shell: bash
      run: |
        if [[ -n "${{ inputs.dependency-groups }}" ]]; then
          uv sync --extra "${{ inputs.dependency-groups }}"
        else
          uv sync --all-groups
        fi
