name: Set Dynamic Version
description: Sets a version suffix based on branch name (e.g. "-dev" or "-feature-xyz")

runs:
  using: "composite"
  steps:
    - name: Set version suffix
      shell: bash
      run: |
        if [[ "${GITHUB_REF##*/}" != "main" ]]; then
          export VERSION_SUFFIX=".dev.${GITHUB_RUN_NUMBER}"
        else
          export VERSION_SUFFIX=""
        fi
        echo "QSFB_VERSION_SUFFIX=$VERSION_SUFFIX" >> "$GITHUB_ENV"
        echo "Using version suffix: $VERSION_SUFFIX"
