name: Bump Patch and Tag
description: Bump the patch version based on VERSION file and create a git tag

inputs:
  dry-run:
    required: false
    default: "false"
    description: Perform a dry run (no tag creation)

  github-token:
    required: true
    description: GitHub token for authentication

outputs:
  new-tag:
    description: "The new tag created (or calculated in dry run)"
    value: ${{ steps.bump.outputs.tag }}

runs:
  using: composite
  steps:

    - name: Configure Git user and auth
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ inputs.github-token }}@github.com/${{ github.repository }}
      shell: bash
  
    - name: Bump Patch Version
      id: bump
      run: |
        TAG=$(uv run scripts/bump_patch.py $( [ "${{ inputs.dry-run }}" = "true" ] && echo "--dry-run" ))
        echo "tag=$TAG" >> $GITHUB_OUTPUT
      shell: bash
