name: Bump Patch and Tag
description: Bump the patch version based on VERSION file and create a git tag

inputs:
  dry-run:
    required: false
    default: "false"
    description: Perform a dry run (no tag creation)

runs:
  using: composite
  steps:

    - name: Configure Git user and auth
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
      shell: bash
  
    - name: Bump Patch Version
      run: |
        if [ "${{ inputs.dry-run }}" = "true" ]; then
          uv run scripts/bump_patch.py --dry-run
        else
          uv run scripts/bump_patch.py
        fi
      shell: bash
